name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#ci-cd'
          config: .github/config/slack.yml
        if: always()
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn semantic-release
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#ci-cd'
          config: .github/config/slack.yml
        if: always()
